In [1]:
import numpy as np
import keras
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from keras import losses
from keras.models import Sequential
from keras.layers import Dense , Dropout

Using TensorFlow backend.


In [2]:
model = Sequential()

In [3]:
path_file = os.path.dirname(os.path.abspath('__file__')) + '/coordibnate_data.csv'
data_file = pd.read_csv(path_file)

In [4]:
data_file.head()

0.1842258564115984  0.68358294695935  0.5453176802294655  91   30  -43  94  \
0            0.025772          0.489946            0.438709  -4   52  -65  90   
1            0.813249          0.797522            0.219998  69   20  -85  72   
2            0.999395          0.872107            0.870772  30   79   22   8   
3            0.794153          0.629818            0.785706  65  100    5  40   
4            0.951330          0.019522            0.453760  -4   79  -54  49   

   61  37  44  23  
0  82  25  75  52  
1  54   9  68  83  
2   5  86  82  59  
3  32  87  21  50  
4  53  21  67  43

In [5]:
x = data_file.iloc[: , 0:9]
y = data_file.iloc[: , 9:]

In [6]:
xtrain , xtest , ytrain , ytest = train_test_split(x , y)

In [7]:
xtest.shape

(250, 9)

In [8]:
len(ytest) , len(ytrain)

(250, 749)

In [9]:
xtrain.shape

(749, 9)

In [10]:
model.add(Dense(128, kernel_initializer='normal',input_dim = xtrain.shape[1], activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(256, kernel_initializer='normal',activation='relu'))
model.add(Dense(2, kernel_initializer='normal',activation='linear'))

Instructions for updating:
Colocations handled automatically by placer.


In [11]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 128)               1280      
_________________________________________________________________
dense_2 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_3 (Dense)              (None, 256)               65792     
_________________________________________________________________
dense_4 (Dense)              (None, 256)               65792     
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 514       
Total params: 166,402
Trainable params: 166,402
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mse'])

In [13]:
model.fit(xtrain , ytrain , epochs = 200 , validation_data = (xtest , ytest))

Instructions for updating:
Use tf.cast instead.
Train on 749 samples, validate on 250 samples
Epoch 1/200
749/749 [==============================] - 2s 3ms/step - loss: 32.5962 - mean_squared_error: 1579.4062 - val_loss: 27.6581 - val_mean_squared_error: 1100.2607
Epoch 2/200
749/749 [==============================] - 0s 148us/step - loss: 26.5079 - mean_squared_error: 991.4787 - val_loss: 27.2499 - val_mean_squared_error: 1029.9922
Epoch 3/200
749/749 [==============================] - 0s 364us/step - loss: 25.7549 - mean_squared_error: 923.0283 - val_loss: 28.8480 - val_mean_squared_error: 1190.9058
Epoch 4/200
749/749 [==============================] - 0s 327us/step - loss: 26.6128 - mean_squared_error: 997.7341 - val_loss: 26.8542 - val_mean_squared_error: 1008.4209
Epoch 5/200
749/749 [==============================] - 0s 277us/step - loss: 25.5043 - mean_squared_error: 906.3382 - val_loss: 26.9757 - val_mean_squared_error: 1007.6370
Epoch 6/200
749/749 [==========================

749/749 [==============================] - 0s 136us/step - loss: 20.9147 - mean_squared_error: 699.6331 - val_loss: 28.9080 - val_mean_squared_error: 1186.7288
Epoch 47/200
749/749 [==============================] - 0s 139us/step - loss: 21.1765 - mean_squared_error: 721.7115 - val_loss: 28.9329 - val_mean_squared_error: 1201.7803
Epoch 48/200
749/749 [==============================] - 0s 138us/step - loss: 20.6249 - mean_squared_error: 687.4633 - val_loss: 29.1268 - val_mean_squared_error: 1207.4781
Epoch 49/200
749/749 [==============================] - 0s 133us/step - loss: 20.6369 - mean_squared_error: 696.9372 - val_loss: 28.6719 - val_mean_squared_error: 1201.8422
Epoch 50/200
749/749 [==============================] - 0s 131us/step - loss: 20.3673 - mean_squared_error: 669.7460 - val_loss: 29.4137 - val_mean_squared_error: 1251.9226
Epoch 51/200
749/749 [==============================] - 0s 139us/step - loss: 20.6577 - mean_squared_error: 692.0781 - val_loss: 28.8096 - val_mean_

749/749 [==============================] - 0s 219us/step - loss: 14.9811 - mean_squared_error: 418.0144 - val_loss: 30.4959 - val_mean_squared_error: 1344.0016
Epoch 94/200
749/749 [==============================] - 0s 232us/step - loss: 14.2040 - mean_squared_error: 394.7345 - val_loss: 30.8909 - val_mean_squared_error: 1397.1348
Epoch 95/200
749/749 [==============================] - 0s 217us/step - loss: 13.6656 - mean_squared_error: 373.9350 - val_loss: 30.8977 - val_mean_squared_error: 1402.9120
Epoch 96/200
749/749 [==============================] - 0s 228us/step - loss: 14.7036 - mean_squared_error: 414.9150 - val_loss: 29.9918 - val_mean_squared_error: 1335.2133
Epoch 97/200
749/749 [==============================] - 0s 246us/step - loss: 14.2015 - mean_squared_error: 396.4501 - val_loss: 30.8990 - val_mean_squared_error: 1417.2092
Epoch 98/200
749/749 [==============================] - 0s 238us/step - loss: 14.0851 - mean_squared_error: 391.2207 - val_loss: 30.7790 - val_mean_

749/749 [==============================] - 0s 152us/step - loss: 8.6943 - mean_squared_error: 181.3692 - val_loss: 30.5707 - val_mean_squared_error: 1413.4507
Epoch 141/200
749/749 [==============================] - 0s 146us/step - loss: 8.6354 - mean_squared_error: 182.8110 - val_loss: 31.4489 - val_mean_squared_error: 1482.9709
Epoch 142/200
749/749 [==============================] - 0s 231us/step - loss: 8.5214 - mean_squared_error: 175.4459 - val_loss: 31.2103 - val_mean_squared_error: 1471.9150
Epoch 143/200
749/749 [==============================] - 0s 236us/step - loss: 8.4363 - mean_squared_error: 168.3773 - val_loss: 31.6370 - val_mean_squared_error: 1506.2436
Epoch 144/200
749/749 [==============================] - 0s 252us/step - loss: 8.4673 - mean_squared_error: 172.6222 - val_loss: 30.9073 - val_mean_squared_error: 1448.5541
Epoch 145/200
749/749 [==============================] - 0s 236us/step - loss: 8.2415 - mean_squared_error: 164.5226 - val_loss: 31.0562 - val_mean_s

749/749 [==============================] - 0s 124us/step - loss: 6.0168 - mean_squared_error: 94.3263 - val_loss: 31.7324 - val_mean_squared_error: 1490.9343
Epoch 188/200
749/749 [==============================] - 0s 132us/step - loss: 6.5410 - mean_squared_error: 107.4735 - val_loss: 31.0174 - val_mean_squared_error: 1447.9044
Epoch 189/200
749/749 [==============================] - 0s 143us/step - loss: 6.6981 - mean_squared_error: 106.0258 - val_loss: 31.5692 - val_mean_squared_error: 1493.1466
Epoch 190/200
749/749 [==============================] - 0s 129us/step - loss: 6.5556 - mean_squared_error: 102.4976 - val_loss: 31.2010 - val_mean_squared_error: 1474.7422
Epoch 191/200
749/749 [==============================] - 0s 127us/step - loss: 5.9388 - mean_squared_error: 92.6985 - val_loss: 31.5116 - val_mean_squared_error: 1494.7437
Epoch 192/200
749/749 [==============================] - 0s 117us/step - loss: 5.7629 - mean_squared_error: 87.2391 - val_loss: 31.1262 - val_mean_squa

In [14]:
ypred = model.predict(xtest)

In [15]:
ytest - ypred

44         23
506 -20.541256 -10.786518
813 -36.383263  41.736637
422  -1.018166 -58.063393
438  13.982812  59.043320
763  38.838839 -32.293049
79   11.036171 -10.698128
283   4.119930 -20.667681
26   29.222446  70.329134
462  41.410618 -36.247818
366  64.454037  17.819550
272 -21.177124 -35.179932
973   9.859200 -39.971352
54   56.021862  -9.149403
186  24.360579 -38.666878
124  29.909996  28.311913
542 -42.754589  19.351013
883 -25.310246 -20.108727
531  24.336586  30.939621
726 -62.071266  16.908844
161  73.905205   2.083792
367 -10.350294 -42.762032
585 -25.035492  82.093813
0    40.423992 -26.968750
282  -5.151232 -39.393703
513 -41.119358  -9.451538
25  -23.926167 -34.386581
603  41.061481 -46.817112
116  -4.464542 -14.722286
622  34.239903  11.683060
683  51.887882 -21.393085
..         ...        ...
621  67.446957 -13.220444
700 -61.960335  -2.063644
777 -14.927505  -3.712633
34   66.137285  74.295630
69   28.004932 -62.265518
637   0.449257  -7.498009
590   4.720535  12.587448
222  34.608562  -6.913212
841 -60.221649 -10.690592
94    7.747116  42.890514
464  50.226753 -29.502026
769  34.610386  35.725994
982  22.733746  -4.740274
170 -60.506416 -14.403366
869  79.291239 -12.057083
412  16.448986 -32.949596
644 -11.572083 -51.328583
287 -35.654167 -56.232384
352 -13.451691 -39.021660
945  43.947155  67.711838
401  -2.362156  -9.091175
309 -25.964745  10.767235
575   9.361252  17.078983
174  18.596245 -57.171070
569  75.195019  -9.195011
37   12.235477  11.340672
328  -6.801006  29.059221
659 -42.824398  -2.668411
473 -12.256565 -15.493240
248   2.541374  62.645996

[250 rows x 2 columns]

In [16]:
from keras.models import load_model

# Creates a HDF5 file 'my_model.h5'
model.save('my_model.h5')

del model

In [22]:

from keras.models import load_model
del model
# Returns a compiled model identical to the previous one
model = load_model('my_model.h5')

In [23]:
model.predict(xtest)

array([[ 25.541256 ,  45.78652  ],
       [ 42.383263 ,  52.263363 ],
       [ 48.018166 , 100.06339  ],
       [ -5.9828124,  40.95668  ],
       [ 17.161161 ,  42.29305  ],
       [ 67.96383  ,  70.69813  ],
       [ 53.88007  ,  26.66768  ],
       [ 45.777554 ,  25.670866 ],
       [ 32.589382 ,  64.24782  ],
       [ 34.545963 ,  69.18045  ],
       [ 77.177124 ,  81.17993  ],
       [ 64.1408   ,  79.97135  ],
       [ 39.978138 ,  54.149403 ],
       [ 11.6394205,  55.666878 ],
       [ 49.090004 ,  13.688087 ],
       [ 42.75459  ,  67.64899  ],
       [ 45.310246 ,  32.108727 ],
       [ 27.663414 ,  68.06038  ],
       [ 93.071266 ,  39.091156 ],
       [ 19.094795 ,  31.916208 ],
       [ 21.350294 ,  83.76203  ],
       [ 39.035492 ,  14.906187 ],
       [ 34.576008 ,  78.96875  ],
       [ 23.151232 ,  39.393703 ],
       [ 50.119358 ,  86.45154  ],
       [ 34.926167 ,  72.38658  ],
       [ 49.93852  ,  46.817112 ],
       [ 37.464542 ,  21.722286 ],
       [  8.760097 ,

In [25]:
model.predict(np.array([[0.21531516644139326,0.15005541484228635,0.7914562008951398,-2.,39.,-62.,76.,55.,65.]]))

array([[50.033047, 37.68506 ]], dtype=float32)

In [24]:
model.predict(np.array([xtest.iloc[0 , :]]))

array([[25.541256, 45.786526]], dtype=float32)

In [20]:
np.array([xtest.iloc[0 , :]])

array([[ 0.68379076,  0.63380769,  0.99909464, 15.        , 70.        ,
        29.        , 69.        , 68.        , 74.        ]])

In [21]:
model.predict(np.array([[  0.64611937,   0.20995504,   0.5158299 ,   7.        ,
          5.        , -37.        ,  38.        ,  29.        ,
         14.        ]]))

array([[45.310246, 32.108727]], dtype=float32)